[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#928374"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#ebdbb2"
yellow = "#fabd2f"

[colors.normal]
black = "#282828"
blue = "#458588"
cyan = "#689d6a"
green = "#98971a"
magenta = "#b16286"
red = "#cc241d"
white = "#a89984"
yellow = "#d79921"

[colors.primary]
background = "#282828"
foreground = "#ebdbb2"

[cursor]
style = { shape = "Block", blinking = "Off" }
blink_interval = 750

[font]
size = 12
bold = { family = "FiraCode Nerd Font", style = "Bold" }
italic = { family = "FiraCode Nerd Font", style = "Italic" }
normal = { family = "FiraCode Nerd Font", style = "Regular" }

[keyboard]
bindings = [
	{ key = "PageUp", mods = "Shift", action = "ScrollPageUp" },
	{ key = "PageDown", mods = "Shift", action = "ScrollPageDown" },
	{ key = "End", mods = "Shift", action = "ScrollToBottom" },
	{ key = "Home", mods = "Shift", action = "ScrollToTop" },
	{ key = "V", mods = "Control", action = "Paste" }
]

[scrolling]
history = 1000
multiplier = 3

[selection]
save_to_clipboard = true

[window]
opacity = 1
class = { instance = "Alacritty", general = "Alacritty" }
padding = { x = 5, y = 5 }
