#!/bin/bash

ID=$(xprop -root | awk '/_NET_ACTIVE_WINDOW\(WINDOW\)/{print $NF}')
TITLE=$(xprop -id $ID | awk '/_NET_WM_NAME/{$1=$2="";print}' | cut -d'"' -f2)

if [[ "$TITLE" != "" ]]
then
	IGNORE=$(echo $TITLE | grep -e ".*Brave$")
	if [[ "$IGNORE" != "" ]]
	then
		TITLE="Brave Browser"
		printf "Brave Browser\n"
	elif [[ $1 ]]
	then
		TITLE=${TITLE:0:$1}
	fi
	printf "$TITLE\n"
fi
