#!/bin/bash

ID=$(xprop -root | awk '/_NET_ACTIVE_WINDOW\(WINDOW\)/{print $NF}')
if [[ $1 ]] 
then
	TITLE=$(xprop -id $ID -len $1 | awk '/_NET_WM_NAME/{$1=$2="";print}' | cut -d'"' -f2)
else
	TITLE=$(xprop -id $ID | awk '/_NET_WM_NAME/{$1=$2="";print}' | cut -d'"' -f2)
fi

if [[ "$TITLE" != "" ]]
then
	IGNORE=$(echo $TITLE | grep -e ".*Brave$")
	if [[ "$IGNORE" != "" ]]
	then
		TITLE="Brave Browser"
		printf "Brave Browser\n"
	else
		printf "$TITLE\n"
	fi
fi
