#!/usr/bin/env perl

use strict;
use warnings;
use utf8;
use Getopt::Long;

binmode(STDOUT, ":utf8");

# default values
my $chip = $ENV{SENSOR_CHIP} || "";
my $temperature = -9999;
my $label = "😀 ";

# Get chip temperature
open (SENSORS, "sensors -u $chip |") or die;
while (<SENSORS>) {
    if (/^\s+temp1_input:\s+[\+]*([\-]*\d+\.\d)/) {
        $temperature = $1;
        last;
    }
}
close(SENSORS);

$temperature eq -9999 and die 'Cannot find temperature';

if ($temperature < 45) {
  $label = '';
} elsif ($temperature < 55) {
  $label = '';
} elsif ($temperature < 65) {
  $label = '';
} elsif ($temperature < 75) {
  $label = '';
} else {
  $label = '';
}

# Print short_text, full_text
print "${label} cpu_tem:";
print " $temperature°C\n";

exit 0;
